export const MAX_CHILD_RELATIONS_PER_RECORD = 100;
export const MAX_CARE_ENTRY_TRIPS = 100;
export const MAX_CARE_ENTRY_COSTS = 100;

export const MAX_TRANSFER_COLLECTION_RECORDS = 50_000;
export const MAX_TRANSFER_TOTAL_RECORDS = 100_000;
export const MAX_TRANSFER_ACTORS = 10_000;
export const MAX_TRANSFER_ACTOR_RELATIONS = 50_000;
