{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "betreuungskalender.fullname" . }}-metrics
  labels:
    {{- include "betreuungskalender.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "betreuungskalender.selectorLabels" . | nindent 4 }}
{{- end }}
